export const GET_SHOP_INFO = 'GET_SHOP_INFO';

export const CHANGE_INDEX = 'CHANGE_INDEX';

export const ADD_SELECT_ITEM = 'ADD_SELECT_ITEM';

export const MINUSS_ELECT_ITEM = 'MINUSS_ELECT_ITEM';

export const CHANGE_SHOW_CHOOSE = 'CHANGE_SHOW_CHOOSE';

export const ADD_SELECT_FOOD = 'ADD_SELECT_FOOD';

export const MINUS_SELECT_FOOD = 'MINUS_SELECT_FOOD';

export const CLEAR_CHOOSE_ITEM = 'CLEAR_CHOOSE_ITEM';

export const GET_COMMENT_DATA = 'GET_COMMENT_DATA';

export const SET_NAV_HEADER_HEIGHT = 'SET_NAV_HEADER_HEIGHT';

export const SET_TAB_HEIGHT = 'SET_TAB_HEIGHT';

export const GET_RESTAURANT_DATA = 'GET_RESTAURANT_DATA';